### ISSUE TITLE
cfo craning crashes the game (macOS only)

### ISSUE THREAD

**Issue by DarthMDev** [toontown-archipelago/toontown-archipelago#70]
will try to debug this myself but any help is much appreciated
```

Assertion failed: !is_empty() at line 228 of built/include/nodePath.I
[CFO Boss Room] Failed to disable back wall.
:TTOffMagicWordManager: Skipping current round...
setting to 0.83 0.7347941176470587 0.3905882352941176 (47 0.5294117647058824 0.83)
setting to 0.83 0.7347941176470587 0.3905882352941176 (47 0.5294117647058824 0.83)
Assertion failed: !point.is_nan() at line 153 of panda/src/collide/collisionEntry.I
Assertion failed: !point.is_nan() at line 181 of panda/src/collide/collisionEntry.I
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/direct/showbase/ShowBase.py", line 2214, in __collisionLoop
    self.cTrav.traverse(self.render)
AssertionError: !point.is_nan() at line 153 of panda/src/collide/collisionEntry.I
:task(error): Exception occurred in PythonTask collisionLoop
:TTOffLauncher: setting panda error code to 12
:TTOffLauncher(warning): Handling Python exception.
:TimeManager: Client disconnect reason 3.
:TimeManager: Client exception: direct.showbase.ShowBase:2214, direct.task.Task:845, direct.task.Task:1167, otp.launcher.LauncherBase:1052, AssertionError: !point.is_nan() at line 153 of panda/src/collide/collisionEntry.I
:OTPClientRepository: Sent disconnect message to server
:OTPClientRepository: Closing connection to server.
:TTOffLauncher: Exception exit.

Traceback (most recent call last):
  File "/Users/michael/github/TTAP/toontown-archipelago/otp/launcher/LauncherBase.py", line 1081, in mainLoop
    self._runTaskManager()
  File "/Users/michael/github/TTAP/toontown-archipelago/otp/launcher/LauncherBase.py", line 1052, in _runTaskManager
    taskMgr.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/direct/task/Task.py", line 629, in run
    self.step()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/direct/task/Task.py", line 579, in step
    self.mgr.poll()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/direct/showbase/ShowBase.py", line 2214, in __collisionLoop
    self.cTrav.traverse(self.render)
AssertionError: !point.is_nan() at line 153 of panda/src/collide/collisionEntry.I

```

**Comment by DarthMDev** [comment]
Fixed in latest development build. Will be in next release
